version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
