services:
  app:
    image: todo-front-dev
    volumes:
      - ./todo-frontend:/usr/src/app
    # NO ports

  server:
    image: todo-back-dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    # NO ports

  mongo:
    image: mongo:6

  redis:
    image: redis:7

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
      - server

